name: chatbot
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  alan_voice: 4.1.1

  cupertino_icons: ^1.0.2
  provider: ^6.0.5
  shared_preferences: ^2.1.1
  flutter_spinkit: ^5.2.0
  iconsax: ^0.0.8
  iconly: ^1.0.1
  speech_to_text: ^6.1.1
  avatar_glow: ^2.0.2
  http: ^0.13.6
  animated_text_kit: ^4.2.2
  url_launcher: ^6.1.11
  flutter_tts: ^3.7.0
  animate_do: ^3.0.2
  flutter_otp_text_field: ^1.1.1
  google_fonts: ^4.0.4
  firebase_core: ^2.13.1
  firebase_auth: ^4.6.2
  get: ^4.6.5

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true
  assets:
    - assets/images/
    - assets/audio_type/

  fonts:
    - family: Cera Pro
      fonts:
        - asset: assets/fonts/Cera-Pro-Bold.otf
        - asset: assets/fonts/Cera-Pro-Medium.otf